import { describe, expect, it } from "vitest";
import { mm, patternCoverage, validateSystem } from "@/engine";
import { MDL_VERSION } from "@/engine/mdl/target";
import { solveSystem } from "@/engine/solve/solveSystem";
import { dotFrit, FIXTURES } from "./fixtures";

/**
 * Structural checks on everything the emitter produces.
 *
 * These cannot prove MDL is semantically valid — only a compiler can, and that
 * job is reserved for CI later — but they catch the mechanical failures that
 * would otherwise only surface as a load error inside 3ds Max.
 */

const sources = FIXTURES.map((f) => ({
  slug: f.slug,
  source: solveSystem(f.input, f.mode).module.source,
  result: solveSystem(f.input, f.mode),
}));

describe.each(sources)("$slug", ({ source, result }) => {
  it("declares the target MDL version first", () => {
    expect(source.split("\n")[0]).toBe(`mdl ${MDL_VERSION};`);
  });

  it("imports exactly the modules it references", () => {
    const imported = new Set([...source.matchAll(/^import ::(\w+)::\*;$/gm)].map((m) => m[1]));
    const referenced = new Set(
      [...source.matchAll(/\b(df|base|state|math|anno|tex)::/g)].map((m) => m[1]),
    );

    for (const name of referenced) {
      expect(imported.has(name), `${name}:: used but never imported`).toBe(true);
    }
    for (const name of imported) {
      expect(referenced.has(name), `::${name}:: imported but never used`).toBe(true);
    }
  });

  it("balances braces and parentheses", () => {
    const withoutComments = source.replace(/^\s*\/\/.*$/gm, "");
    const count = (re: RegExp) => (withoutComments.match(re) ?? []).length;
    expect(count(/\(/g)).toBe(count(/\)/g));
    expect(count(/\{/g)).toBe(count(/\}/g));
    expect(count(/\[/g)).toBe(count(/\]/g));
  });

  it("exports every material the solver produced", () => {
    const exported = [...source.matchAll(/^export material (\w+)\(/gm)].map((m) => m[1]);
    expect(exported).toEqual(result.materials.map((m) => m.name));
    expect(new Set(exported).size).toBe(exported.length); // names unique within a module
  });

  it("contains no unresolved or invalid numbers", () => {
    const code = source.replace(/^\s*\/\/.*$/gm, "");
    for (const marker of ["NaN", "undefined", "null", "Infinity", "TODO", "[object"]) {
      expect(code).not.toContain(marker);
    }
  });

  it("writes float literals MDL will accept", () => {
    // Every numeric argument must carry a decimal point; a bare integer where a
    // float is expected is a compile error in MDL.
    const args = [...source.matchAll(/^\s+\w+: (-?\d[\d.]*)(,?)$/gm)].map((m) => m[1]);
    for (const value of args) {
      expect(value, `"${value}" is missing a decimal point`).toContain(".");
    }
  });

  it("never reaches for world-space state functions", () => {
    // state::position() and state::meters_per_scene_unit() collapse to
    // constants in Iray's cutout context and render the surface invisible
    // (render-confirmed, docs/iray-findings.md §7.1). UV space is the only
    // reliable frame for generated patterns.
    expect(source).not.toContain("state::position");
    expect(source).not.toContain("state::meters_per_scene_unit");
  });

  it("stamps a content revision into the module filename", () => {
    expect(result.module.fileName).toMatch(/_r[0-9a-f]{6}\.mdl$/);
  });

  it("references textures by module-relative path", () => {
    for (const match of source.matchAll(/texture_2d\("([^"]+)"/g)) {
      expect(match[1].startsWith("./")).toBe(true);
      expect(match[1]).not.toContain(".."); // never escape the module folder
    }
  });

  it("keeps every generated identifier valid", () => {
    const identifiers = [
      ...[...source.matchAll(/^export material (\w+)/gm)].map((m) => m[1]),
      ...[...source.matchAll(/^export float (\w+)/gm)].map((m) => m[1]),
    ];
    for (const id of identifiers) {
      expect(id).toMatch(/^[A-Za-z_][A-Za-z0-9_]*$/);
    }
  });

  it("documents its provenance in comments", () => {
    expect(source).toContain("Generated by glass2mdl");
    expect(source).toContain("Data sheet input:");
    expect(source).toContain("Fitted result:");
  });
});

describe("frit exports", () => {
  it("ships the mask file alongside the material that references it", () => {
    const solved = solveSystem(
      FIXTURES.find((f) => f.slug === "mask-frit-volumetric")!.input,
      "volumetric",
    );
    expect(solved.textures).toHaveLength(1);
    expect(solved.module.source).toContain(`./${solved.textures[0].fileName}`);
  });

  it("exposes a scale parameter for procedural patterns", () => {
    const solved = solveSystem(
      FIXTURES.find((f) => f.slug === "dot-frit-volumetric")!.input,
      "volumetric",
    );
    expect(solved.module.source).toContain("uniform float frit_pattern_scale");
  });

  it("saturates procedural coverage where features outgrow their spacing", () => {
    // Dots on a square grid overlap past π/4 ≈ 78.5% coverage; the analytic
    // number caps at 1 so the UI never reports more frit than glass.
    expect(patternCoverage({ kind: "dots", dotDiameter: mm(10), spacing: mm(10) })).toBeCloseTo(
      Math.PI / 4,
      6,
    );
    expect(patternCoverage({ kind: "dots", dotDiameter: mm(15), spacing: mm(10) })).toBe(1);
    expect(
      patternCoverage({ kind: "lines", lineWidth: mm(14), spacing: mm(10), orientation: "horizontal" }),
    ).toBe(1);
  });

  it("warns when the pattern crosses the overlap threshold", () => {
    const issues = validateSystem({
      ...dotFrit,
      frit: {
        ...dotFrit.frit!,
        pattern: { kind: "dots", dotDiameter: mm(13), spacing: mm(10) },
      },
    });
    expect(issues.some((i) => i.code === "frit-dots-overlap")).toBe(true);
  });

  it("needs no pattern function for uniform coverage", () => {
    const solved = solveSystem(
      FIXTURES.find((f) => f.slug === "uniform-frit-planar")!.input,
      "planar",
    );
    expect(solved.module.source).not.toContain("export float");
    expect(solved.textures).toHaveLength(0);
  });
});
