import { locateSurface } from "../physics/assembly";
import { luminance } from "../physics/color";
import { litePositionNames } from "../mdl/naming";
import { MDL_VERSION, TOOL_NAME, TOOL_VERSION } from "../mdl/target";
import type { MaterialIR } from "../types/ir";
import type { SolverWarning } from "../types/issues";
import type { DerivedOptics } from "../types/optics";
import type { ExportMode, GlazingSystemInput } from "../types/system";

const pct = (v: number) => `${(v * 100).toFixed(1)}%`;

/**
 * The README shipped in every download.
 *
 * It has to carry everything the .mdl cannot: which material goes on which
 * lite, how to get the files where Iray will find them, and which
 * approximations are in play. A download that arrives without this is a set of
 * files nobody can assign correctly.
 */
export function buildReadme(options: {
  input: GlazingSystemInput;
  mode: ExportMode;
  materials: MaterialIR[];
  derived: DerivedOptics;
  warnings: SolverWarning[];
  moduleFileName: string;
  textureFileNames: string[];
}): string {
  const { input, mode, materials, derived, warnings, moduleFileName, textureFileNames } = options;
  const lines: string[] = [];

  lines.push(
    `${input.name}`,
    `${"=".repeat(input.name.length)}`,
    "",
    `Generated by ${TOOL_NAME} ${TOOL_VERSION} (${mode} export, MDL ${MDL_VERSION}).`,
    "",
    "FILES",
    "-----",
    `  ${moduleFileName}`,
    ...(mode === "volumetric"
      ? [
          "  glass2mdl_apply.py  (the 3ds Max apply script; run it there)",
          "  bind_manifest.json  (drives the apply script)",
        ]
      : []),
    ...textureFileNames.map((f) => `  ${f}`),
    "  README.txt  (this file)",
    "",
    "INSTALLING",
    "----------",
    "1. Keep every file in this folder together: the .mdl references the",
    "   images next to it by relative path.",
    "2. Put the folder DIRECTLY under a folder listed as an MDL search path",
    "   in Iray for 3ds Max (Iray+ settings > MDL search paths; this",
    "   folder's parent on disk is the search path).",
    "3. Restart the material browser if it was already open, then find the",
    "   materials by the names below.",
    ...(mode === "volumetric"
      ? [
          "4. In 3ds Max: Scripting > Run Script > glass2mdl_apply.py (from",
          "   this folder). A window walks the rest: select your glazing,",
          "   Tag + color check, flip anything blue-out, choose the bundled",
          "   bind_manifest.json (placement is verified), Bind.",
        ]
      : []),
    "",
    "The .mdl filename ends in a revision code that changes with the",
    "content. 3ds Max caches loaded modules for the whole session, so this",
    "is what lets a re-export show up without restarting Max. Old revisions",
    "left in the folder can be deleted.",
    "",
    "MATERIALS",
    "---------",
  );

  if (mode === "planar") {
    lines.push(
      "This export models the whole assembly as one flat surface.",
      "",
      `  ${materials[0].name}`,
      `      Apply to a single plane with no thickness, one face per opening.`,
      "      Face normals must point outward (toward the exterior); the",
      "      interior appearance comes from the material's backface.",
      "",
      "Do not apply this material to a solid or an extruded lite: the",
      "measured numbers already account for every internal reflection, and",
      "a solid would apply them twice.",
    );
  } else {
    const positions = litePositionNames(input.lites.length);
    lines.push(
      "This export gives every lite its own material. Model each lite as a",
      "closed solid at its real thickness, spaced by the gap widths below.",
      "",
    );
    input.lites.forEach((lite, i) => {
      const surfaces = `#${i * 2 + 1} and #${i * 2 + 2}`;
      lines.push(
        `  ${materials[i].name}`,
        `      Lite ${i + 1} (${positions[i]}), ${lite.thickness}mm, surfaces ${surfaces}`,
        `      Body transmittance ${pct(luminance(derived.lites[i].internalTransmittance))}`,
      );
      if (lite.coating) {
        lines.push(
          "      Coated: assign per face via a Multi-Sub-Object on the solid's",
          "      Material IDs: ID 1 exterior face (interior_face off), ID 2",
          "      cavity/interior face (interior_face on), ID 3 edges (off).",
          "      Its volume also carries the coating's absorption, not just",
          "      the body transmittance above.",
        );
      }
      const gap = input.gaps[i];
      if (gap) lines.push(`      → then a ${gap.width}mm gap`);
      lines.push("");
    });

    if (input.frit) {
      const decal = materials[materials.length - 1];
      const { lite, face } = locateSurface(input.frit.surface);
      lines.push(
        `  ${decal.name}`,
        `      Frit, for surface #${input.frit.surface}: the ${
          face === "front" ? "exterior" : "interior"
        }-facing face of lite ${lite + 1}.`,
        "      Create a flat plane matching the glass outline, offset it about",
        "      0.1mm off that face so the two surfaces are not coincident, and",
        "      assign this material to it.",
        "",
      );
    }

    lines.push(
      "Thickness matters here: absorption is specified per meter of travel,",
      "so a lite modeled thicker or thinner than its real dimension will come",
      "out the wrong darkness. The scene's system-unit scale must be honest",
      "for the same reason: imperial scenes are fine, but 6mm of glass must",
      "really measure 0.006m in Iray.",
      "",
      "bind_manifest.json describes every material here for the glass2mdl",
      "3ds Max apply script, which tags face Material IDs and creates and",
      "assigns the Iray+ materials automatically. Without it, assign the",
      "materials by hand as listed above.",
    );
  }

  if (input.frit && materials.some((m) => m.moduleFunctions.length)) {
    lines.push(
      "",
      "FRIT PATTERN SCALE",
      "------------------",
      "The pattern is authored in real millimeters, assuming one UV unit",
      "equals one meter. In 3ds Max that means a UVW Map modifier set to",
      "1.0m x 1.0m, or Real-World Map Size enabled.",
      "",
      "If the pattern comes out the wrong size, change the material's",
      "'Frit pattern scale' parameter instead of regenerating: 2.0 makes the",
      "pattern twice as large, 0.5 half as large.",
    );
  }

  lines.push(
    "",
    "WHAT WAS FITTED",
    "---------------",
    "Cutsheet values you entered, and what the generated materials produce:",
    "",
    `                          entered     fitted`,
    `  Transmittance (VLT)     ${pct(input.assembly.tvis).padStart(7)}   ${pct(
      luminance(derived.recomputed.t),
    ).padStart(7)}`,
    `  Reflectance, exterior   ${pct(input.assembly.rvisExt).padStart(7)}   ${pct(
      luminance(derived.recomputed.rFront),
    ).padStart(7)}`,
    `  Reflectance, interior   ${pct(input.assembly.rvisInt).padStart(7)}   ${pct(
      luminance(derived.recomputed.rBack),
    ).padStart(7)}`,
  );

  if (derived.residual.max > 0.02) {
    lines.push(
      "",
      `  The fit is off by up to ${(derived.residual.max * 100).toFixed(1)} percentage points.`,
      "  That usually means the entered numbers describe a construction",
      "  different from the one configured. Check the lite count, the",
      "  coating's surface, and the substrate tints.",
    );
  }

  if (warnings.length) {
    lines.push("", "NOTES AND APPROXIMATIONS", "------------------------");
    for (const warning of warnings) {
      lines.push(...wrap(warning.message, 72, "  "), "");
    }
  }

  lines.push(
    "",
    "These materials reproduce visible-light appearance. They are not a",
    "substitute for thermal or daylight-factor analysis.",
    "",
  );

  return lines.join("\n");
}

/** Soft-wrap text for a fixed-width README. */
function wrap(text: string, width: number, indent: string): string[] {
  const words = text.split(/\s+/);
  const out: string[] = [];
  let line = indent;

  for (const word of words) {
    if (line.length + word.length + 1 > width && line.trim()) {
      out.push(line.trimEnd());
      line = indent;
    }
    line += `${word} `;
  }
  if (line.trim()) out.push(line.trimEnd());
  return out;
}
