import { linearRGBToHex, maxChannel, scaleRGB, luminance } from "../physics/color";
import { describeColorSpec } from "../physics/colorimetry";
import { absorptionCoefficient } from "../physics/slab";
import { TOOL_NAME, TOOL_VERSION } from "../mdl/target";
import { SUBSTRATE_LABELS } from "../physics/constants";
import type { LayerIR } from "../types/ir";
import type { DerivedOptics, RGB } from "../types/optics";
import type { AssemblyFit } from "../physics/assembly";
import { fitResidual, spandrelAppearance } from "../physics/assembly";
import type { ExportMode, GlazingSystemInput, SpandrelInput } from "../types/system";

/** Glossy-metal roughness for a "metallic" pan finish: brushed, not a mirror. */
export const METALLIC_PAN_ROUGHNESS = 0.3;

/** The BSDF a spandrel finish lowers to. */
export function finishLayer(spandrel: SpandrelInput, finish: RGB): LayerIR {
  if (spandrel.kind === "back-pan" && spandrel.finish === "metallic") {
    return { kind: "metal", color: finish, roughness: METALLIC_PAN_ROUGHNESS };
  }
  return { kind: "diffuse", color: finish };
}

/** "RAL 7024 (#4A4D4F)" or "swatch #4A4D4F": how the finish colour was given. */
export function describeFinishColor(spandrel: SpandrelInput, finish: RGB): string {
  const hex = linearRGBToHex(finish).toUpperCase();
  if (spandrel.colorLabel) return `${spandrel.colorLabel} (${hex})`;
  return describeColorSpec(spandrel.color) ?? `swatch ${hex}`;
}

/** One line naming the finish, for headers and the README. */
export function describeFinish(spandrel: SpandrelInput, finish: RGB): string {
  const color = describeFinishColor(spandrel, finish);
  return spandrel.kind === "flood-coat"
    ? `flood coat on surface #${spandrel.surface}, ${color}`
    : `${spandrel.finish} back pan ${spandrel.cavity}mm behind the glass, ${color}`;
}

/**
 * MDL's custom_curve_layer takes a scalar reflectivity, so a colored
 * reflectance is split into a level and a hue: the brightest channel becomes
 * normal_reflectivity and the color is normalized against it, so their product
 * reproduces the fitted RGB reflectance exactly.
 *
 * Both places this is used put a transmission-only BSDF underneath, so the
 * layer owns all of the reflection and the fitted value comes through intact.
 */
export type CoatingLayerIR = Extract<LayerIR, { kind: "fresnel-coating" }>;

export function coatingLayer(reflectance: RGB): CoatingLayerIR {
  const peak = maxChannel(reflectance);
  const color = peak > 1e-6 ? scaleRGB(reflectance, 1 / peak) : { r: 1, g: 1, b: 1 };

  return {
    kind: "fresnel-coating",
    normalReflectivity: Math.min(1, Math.max(0, peak)),
    grazingReflectivity: 1,
    reflectColor: color,
  };
}

/**
 * Pre-divide a transmission tint by the light the layer above it keeps.
 *
 * Same mixing rule seen from the other side: a coating layered at weight w
 * passes only `(1-w)` of the base through, so the base tint must be raised to
 * land on the measured transmittance. Returns the compensated tint plus
 * whether it had to be clamped, since a clamp means the target is out of reach.
 */
export function compensateForLayer(
  tint: RGB,
  layerWeight: number,
): { tint: RGB; clamped: boolean } {
  const passthrough = Math.max(1e-6, 1 - layerWeight);
  const raised = scaleRGB(tint, 1 / passthrough);
  const peak = maxChannel(raised);
  if (peak <= 1) return { tint: raised, clamped: false };
  return { tint: scaleRGB(raised, 1 / peak), clamped: true };
}

/** Beer-Lambert absorption per meter, per channel. */
export function volumeAbsorption(internalT: RGB, thicknessMm: number): RGB {
  const d = thicknessMm / 1000;
  return {
    r: absorptionCoefficient(internalT.r, d),
    g: absorptionCoefficient(internalT.g, d),
    b: absorptionCoefficient(internalT.b, d),
  };
}

const pct = (v: number) => `${(v * 100).toFixed(1)}%`;

/**
 * Header written above every generated material: what was asked for, what came
 * out, and which approximations are baked in. A generated file should be
 * enough on its own to reconstruct or question the result.
 */
export function provenanceComments(
  input: GlazingSystemInput,
  mode: ExportMode,
  fit: AssemblyFit,
  extraNotes: string[] = [],
): string[] {
  const residual = fitResidual(fit, input);
  const lines = [
    `Generated by ${TOOL_NAME} ${TOOL_VERSION} - ${mode} export`,
    `System: ${input.name}`,
    "",
    "Data sheet input:",
    `  Visible transmittance (VLT): ${pct(input.assembly.tvis)}`,
    `  Visible reflectance, exterior: ${pct(input.assembly.rvisExt)}`,
    `  Visible reflectance, interior: ${pct(input.assembly.rvisInt)}`,
  ];

  input.lites.forEach((lite, i) => {
    const coating = lite.coating
      ? `, ${lite.coating.kind} coating on surface #${lite.coating.surface}`
      : "";
    lines.push(`  Lite ${i + 1}: ${lite.thickness}mm ${SUBSTRATE_LABELS[lite.substrate]}${coating}`);
    const gap = input.gaps[i];
    if (gap) lines.push(`  Gap ${i + 1}: ${gap.width}mm`);
  });

  if (input.frit) {
    lines.push(
      `  Frit: ${input.frit.pattern.kind} on surface #${input.frit.surface}, opacity ${pct(input.frit.opacity)}`,
    );
  }

  const spandrel = spandrelAppearance(fit, input);
  if (input.spandrel && spandrel) {
    lines.push(`  Spandrel: ${describeFinish(input.spandrel, spandrel.finish)}`);
  }

  lines.push(
    "",
    "Fitted result:",
    `  Transmittance: ${pct(luminance(fit.achieved.t))} (residual ${(residual.tvis * 100).toFixed(2)} pts)`,
    `  Reflectance ext: ${pct(luminance(fit.achieved.rFront))} (residual ${(residual.rvisExt * 100).toFixed(2)} pts)`,
    `  Reflectance int: ${pct(luminance(fit.achieved.rBack))} (residual ${(residual.rvisInt * 100).toFixed(2)} pts)`,
  );

  if (spandrel) {
    lines.push(
      `  Spandrel reads as, from outside: ${pct(luminance(spandrel.readsAs))} (${linearRGBToHex(spandrel.readsAs).toUpperCase()}); the finish colour is taken as given, nothing transmits`,
    );
  }

  if (extraNotes.length) lines.push("", "Notes:", ...extraNotes.map((n) => `  - ${n}`));
  return lines;
}

/** Per-lite numbers for the UI breakdown panel and the preview shader. */
export function buildDerived(input: GlazingSystemInput, fit: AssemblyFit): DerivedOptics {
  return {
    lites: input.lites.map((lite, i) => {
      const internalT = fit.internalT[i];
      const isCoated = fit.coating?.location.lite === i;
      return {
        index: i,
        thickness: lite.thickness,
        internalTransmittance: internalT,
        absorptionCoefficient: volumeAbsorption(internalT, lite.thickness),
        ...(isCoated && fit.coating
          ? {
              coatingR0: maxChannel(fit.coating.rExt),
              coatingColor: lite.coating?.reflectedColor ?? fit.coating.rExt,
            }
          : {}),
      };
    }),
    coating: fit.coating
      ? {
          surface: input.lites.find((l) => l.coating)?.coating?.surface ?? 0,
          transmission: fit.coating.tau,
          reflectanceExt: fit.coating.rExt,
          reflectanceInt: fit.coating.rInt,
        }
      : undefined,
    recomputed: { t: fit.achieved.t, rFront: fit.achieved.rFront, rBack: fit.achieved.rBack },
    residual: fitResidual(fit, input),
    spandrel: spandrelAppearance(fit, input),
  };
}
